# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-pv
# spec:
#   capacity:
#     storage: 2Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Recycle
#   hostPath:
#     path:    /var/lib/postgresql/data
#     type: DirectoryOrCreate

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pvc
#   namespace: database
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: standard-rwx

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: example-storage-class
  claimRef:
    name: gcs-fuse-csi-static-pvc
  # mountOptions:
  #   - implicit-dirs
  #   - uid=1001
  #   - gid=3003
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: my-bucket-name
    readOnly: false