# service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: database
spec:
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

