apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: database
spec:
  replicas: 2
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          envFrom:
            - configMapRef:
                name: postgres-configmap
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "250Mi"
              cpu: "500m"
      volumes:
        - name: postgres-pv
          hostPath:
            path:    /var/lib/postgresql/data
            type: DirectoryOrCreate