apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
      # team: devops
    
  template:
    metadata:
      labels:
        component: postgres
        
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops

      containers:
        - name: postgres
          image: postgres:13
          envFrom:
            - configMapRef:
                name: postgres-configmap
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pvc
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "3Gi"
              cpu: "500m"
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
      
    