#secret
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: airflow
type: Opaque
data:
  connection: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FkaXMtYWlyZmxvdzphZGlzLWFpcmZsb3dAcG9zdGdyZXMtc2VydmljZS5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3Bvc3RncmVzL2Ri
  # ostgresql+psycopg2://adis-airflow:adis-airflow@postgres-service.database.svc.cluster.local:5432/postgres/db