name: cicd for data engineering worfkow
on:  workflow_dispatch

jobs:
    Terraform-cicd:
      runs-on: ubuntu-latest

      defaults:
        run:
          shell: bash
          working-directory: ./terraform
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Terraform Init
          run: |
            pwd
            ls -la
            terraform init
          env: 
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
        - name: Terraform Plan
          run: |
            terraform plan --var-file variables.tfvars
          env: 
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Apply
          if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
          run: |
            terraform apply --var-file variables.tfvars -auto-approve
          env: 
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    
    Automation-cicd:
      runs-on: ubuntu-latest
      needs: Terraform-cicd
      defaults:
        run:
          shell: bash
          
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Run script
          run: |
            echo "Hello World!"
         