name: cicd for data engineering worfkow
on:  workflow_dispatch

jobs:
    Terraform-cicd:
      runs-on: ubuntu-latest

      defaults:
        run:
          shell: bash
          working-directory: /home/runner/work/DE-Covid19/DE-Covid19/terraform/terraform
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Terraform Init
          run: |
            pwd
            ls -la
            terraform init
          env: 
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        