name: cicd for data engineering worfkow
on:  workflow_dispatch

jobs:
    Terraform-cicd:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        # - uses: hashicorp/setup-terraform@v3
        
        - name: Setup Terraform
          working-directory: ./terraform
          run: |
            pwd
            ls -la
        